<!DOCTYPE html>
<html>
<head>
	<title>STUDENT'S AWARD</title>

	<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
	<main>
<div class="row">	
<div>
	<center><h3>Student's Award <?php if($from != 'All' && $to != 'All'): ?> (<?php echo e($from); ?> - <?php echo e($to); ?>)<?php endif; ?></h3></center>
</div>
<div>
	<?php 
		if($scope)
			echo '<span class="filters"><strong>Scope:</strong> '.$scope.'</span>';
		if($category)
			echo '<span class="filters"><strong>Category:</strong> '.$category.'</span>';

	 ?>
	</div>
	<table class="bordered" style="table-layout: fixed;">
		<tr style="font-size: 9pt;">
			<th style="width: 2%;"></th>

			<th style="width: 11%;">Student Name</th>
			<?php 
				if(!$scope){
					echo "<th style='width: 7%;'> Scope</th>";
				}
			 ?>
			<?php 
				if(!$category){
					echo "<th style='width: 7%;'> Category</th>";
				}
			 ?>
			 <th style="width: 7%;">Award</th>
			 <th style="width: 9%;">Classification</th>
			 <th style="width: 16%;">Competition</th>
			 <th style="width: 16%;">Award Giving Body</th>
			<th style="width: 9%;">Date Awarded</th>
			<th style="width: 16%;">Venue</th>
			
		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';

				echo '
					  	<td>'.$q->first_name.', '.$q->middle_initial.'. '.$q->last_name.'</td>';
						if(!$scope){
							echo '<td>'.$q->scope.'</td>';
						}
				
						if(!$category){
							echo '<td>'.$q->category.'</td>';
						}	
				echo '
					  	<td>'.$q->award.'</td>';
				echo '
					  	<td>'.$q->classification.'</td>';	
				echo '
					  	<td>'.$q->title_competitions.'</td>';	
				echo '
					  	<td>'.$q->award_giving_body.'</td>';	
				echo '
					  	<td>'.date('M. d, Y', strtotime($q->date_awarded)).'</td>';
				echo '
					  	<td>'.$q->venue.'</td>
					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?>

		</label>
	</div>
</div>
	</main>
</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/Award\Resources/views/reports/useraward-report.blade.php ENDPATH**/ ?>