<!DOCTYPE html>
<html>
<head>
	<title></title>
<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
	   <main>
<div class="row">	
<div>
	<center><h3><?php echo e($exam); ?></h3></center>
</div>
<div>
	</div>
	 <table id="history_table"  class="display compact cell-border" style="text-align: center;">
        <thead>
          <tr>
            <th colspan="2">Date Taken</th>
            <th colspan="4"><center>First Takers</center></th>
            <th>UB Passsing<br>Percentage<br>(First Takers)</th>
            <th colspan="4"><center>Total No. of Takers</center></th>
            <th>UB Overall<br>Passsing<br>Percentage</th>
            <th>National<br>Passsing<br>Percentage</th>
          </tr>
          <tr>
            <th>Month</th>
            <th>Year</th>
            <th>Passed</th>
            <th>Failed</th>
            <th>Con</th>
            <th>Total</th>
            <th></th>
            <th>Passed</th>
            <th>Failed</th>
            <th>Con</th>
            <th>Total</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>';
				echo '
						  <td>'.$q->exam_month.'</td>';
					
				echo '
					  	<td>'.$q->exam_year.'</td>';

				echo '
					  	<td>'.$q->ftaker_passed.'</td>';
					  
				echo '
					  	<td>'.$q->ftaker_failed.'</td>';
					  
				echo '
						  <td>'.$q->ftaker_cond.'</td>';
				$sum1 = $q->ftaker_passed+$q->ftaker_failed+$q->ftaker_cond;
			if($sum1 != 0){
				$percent1 = ( $q->ftaker_passed / $sum1)*100;
			}else{
				$percent1 = 0;
			}
				echo '
					  	<td>'.$sum1.'</td>';
                  
				echo '
					 	<td>'.round($percent1, 2).'%'.'</td>';

				echo '
					  	<td>'.$q->total_passed.'</td>';
					  
				echo '
					  	<td>'.$q->total_failed.'</td>';
					  
				echo '
					  	<td>'.$q->total_cond.'</td>';
				$sum2 = $q->total_passed+$q->total_failed+$q->total_cond;
				if($sum2 != 0){
					$percent2 = ($q->total_passed/$sum2)*100;
				}else{
					$percent2 = 0;
				}
				
				echo '
					  	<td>'.$sum2.'</td>';
				echo '
					  	<td>'.round($percent2, 2).'%'.'</td>';
					  
				echo '
					  	<td>'.$q->national_percent.'%'.'</td>
					  </tr>';
			}
		 ?>
		</tbody>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?>

		</label>
	</div>
</div>
	   </main>

</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/BoardExam\Resources/views/reports/history-report.blade.php ENDPATH**/ ?>