<!DOCTYPE html>
<html>
<head>
	<title>BOARD TOPNOTCHERS</title>
<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<main>
<div class="row">	
<div>
	<?php 
	if($month)
	echo '<span class="filters"><strong>Month:</strong> '.$month.'</span>';
	   if($year)
			echo '<span class="filters"><strong>Year:</strong> '.$year.'</span>';
		if($rank)
			echo '<span class="filters"><strong>Rank:</strong> '.$rank.'</span>';	
	 ?>
	</div>
	<?php if($var != ""): ?>
	<?php $C = count($var); ?>
	<?php for($i=0; $i < $C; $i++): ?>
	<?php $var1 = $var[$i];?>
	<div>
		<center><h3> <?php if($var1 == "SBT"): ?>
			Summary of Board Topnotchers 
			<?php elseif($var1 == "STS"): ?>
			Summary of Top Schools 
			<?php else: ?>
			Universiy of Baguio Board Topnotchers 
			<?php endif; ?>
			<?php if($min != "All"): ?>(<?php echo e($min); ?>-<?php echo e($max); ?>)<?php endif; ?>
			</h3></center>
		</div>
	<?php if($var1 == "SBT"): ?>
	 <table  class="display compact cell-border" style="text-align: center;">
        <thead>
          <tr>
            <th>Program</th>
            <?php 
				if($min != 'All'){	
					$x = $min;
					$y = $max;
					for($x; $x <= $y; $x++){
						echo '<th>'.$x.'</th>';
					}
				}
			 ?>
           </tr>
        </thead>
         <tbody>
		<?php 
		$queryBuilder = $queryBuilder->where('rank','>',0);
          
			foreach ($queryBuilder as $q) {
				
			$x =$min;
			$y =$max;
				echo '<tr>
						  <td>'.$q->licensure_exam.'</td>';
				for($x; $x <= $y; $x++){
					if($q->exam_year == $x){
					echo '<td> Rank '.$q->rank.'</th>';
					}else{
						echo '<td></td>';
					}
				}	
				echo '
					  </tr>';
			}
		 ?>
		</tbody>
	</table>
	<?php elseif($var1 == "STS"): ?>
	<table  class="display compact cell-border" style="text-align: center;">
        <thead>
          <tr>
            <th>Program</th>
            <?php 
				if($min != 'All'){	
					$x = $min;
					$y = $max;
					for($x; $x <= $y; $x++){
						echo '<th>'.$x.'</th>';
					}
				}
			 ?>
           </tr>
        </thead>
         <tbody>
		<?php 
		$queryBuilder = $queryBuilder->where('school_rank','>',0);
			foreach ($queryBuilder as $q) {
				
			$x =$min;
			$y =$max;
				echo '<tr>
						  <td>'.$q->licensure_exam.'</td>';
				for($x; $x <= $y; $x++){
					if($q->exam_year == $x){
					echo '<td> Rank '.$q->school_rank.'</th>';
					}else{
						echo '<td></td>';
					}
				}	
				echo '
					  </tr>';
			}
		 ?>
		</tbody>
	</table>
<?php else: ?>
		<table id="history_table"  class="display compact cell-border" style="text-align: center;">
	 <?php $__currentLoopData = $licensure_exam; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $le): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <thead>
			<tr>
				<?php 
				if(!$rank || !$min){
				 echo "<th colspan='3' style='text-align: left;'>$le</th>";
				}else
					echo "<th colspan='2' style='text-align: left;'>$le</th>";
				?>
			</tr>
          <tr>
		  
		  <?php 
		  		echo "<th>Name</th>";
			 ?>
            <th>Examination Date</th>
            <?php 
				if(!$rank){
					echo "<th>Rank</th>";
				}
			 ?>
           </tr>
        </thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->licensure_exam == $le){
				$count++;
				echo '<tr>
					  	<td>'.$q->name.'</td>
						
					  	<td>'.$q->exam_month.' '.$q->exam_year.'</td>';
						
					  
				if(!$rank){
					if($q->rank == 1)
						$sup = 'st';
				elseif($q->rank == 2)
						$sup = 'nd';
					elseif($q->rank == 3)
					$sup = 'rd';
					else
					$sup = 'th';
				 echo '<td>'.$q->rank.'<sup>'.$sup.'</sup> Place </td>';
						}
				echo '
					  </tr>';
					}
			}
		 ?>
		</tbody>
		<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
	</table>
	<?php endif; ?>
	<?php endfor; ?>
	<?php endif; ?>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?>

		</label>
	</div>
</div>
</main>
</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/BoardExam\Resources/views/reports/topnotcher-report.blade.php ENDPATH**/ ?>