
<!DOCTYPE html>
<html>
<head>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title></title>
	<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
	<main>
<body>
<div class="row">
<?php if($school): ?>
<center><strong><?php echo e($list->school_name); ?> Academic Programs</strong></center><br>
	<table>
        <tr>
			<th style="width:20%;">Program Code</th>
			<th style="width:80%;">Program Description</th>
		</tr>
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
                if($q->school_id == $list->id){
				echo '<tr>';
							echo '<td>'.$q->acad_prog_code.'</td>';
						
				echo '
					  	<td>'.$q->acad_prog.'</td>

                      </tr>';
                    }
			}
         ?>
    </table><br>
<?php else: ?>
<center><h3>List of Schools and Academic Programs</h3></center>
<?php $category = ['Graduate Programs','Undergrad Program','Basic Educatioon'] ?>
<?php for($i = 0; $i < count($category); $i++): ?>
<strong><?php echo e($category[$i]); ?></strong>
	<table>
		<tr>
			<th style="width:15%;">School Code</th>
			<th style="width:15%;">Program Code</th>
			<th style="width:70%;">Program Description</th>
		</tr>
<?php $__currentLoopData = $list; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $l): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<?php $f = substr($l->school_name, 0, 1); ?>
 <?php if($i == 0 ): ?>
	<?php if($l->school_code == 'GS'): ?>
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->school_id == $l->id){
				echo '<tr>
					<td>'.$q->school_code.'</td>
					<td>'.$q->acad_prog_code.'</td>
					<td>'.$q->acad_prog.'</td>

					</tr>';
					}
			}
		?>
		<?php endif; ?>
 <?php elseif($i == 1): ?>
	<?php if($f == 'S'): ?>
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->school_id == $l->id){
					echo '<tr>
					<td>'.$q->school_code.'</td>
					<td>'.$q->acad_prog_code.'</td>
					<td>'.$q->acad_prog.'</td>

					</tr>';
					}
				}
		?>
	<?php endif; ?>
<?php else: ?>
	<?php if($f != 'S' && $l->school_code != 'GS'): ?>
	<?php 
		$count = 0;
		foreach ($queryBuilder as $q) {
			if($q->school_id == $l->id){
				echo '<tr>
				<td>'.$q->school_code.'</td>
				<td>'.$q->acad_prog_code.'</td>
				<td>'.$q->acad_prog.'</td>

				  </tr>';
				}
		}
	 ?>
	 <?php endif; ?>
	<?php endif; ?>
	<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</table><br>
	<?php endfor; ?>
<?php endif; ?>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
	   <?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
	   <label><?php
	   
		date_default_timezone_set('Asia/Hong_Kong');
		echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
	</div>
</div>
		</main>
</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/Accreditation\Resources/views/reports/acadprog-report.blade.php ENDPATH**/ ?>