<!DOCTYPE html>
<html>
<head>
	<title>UNIVERSITY EMPLOYEES</title>
	<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
	<main>
<div class="row">
<div>
	<center><h3>University Employees</h3></center>
</div>
<div>
	<?php 

		if($school)
			echo '<span class="filters"><strong>School / Department:</strong> '.$school.'</span>';
		if($sem)
			echo '<span class="filters"><strong>Semester:</strong> '.$sem.'</span>';
		if($schoolyear)
			echo '<span class="filters"><strong>School Year:</strong> '.$schoolyear.'</span>';

		?>
	</div>
	<table class="bordered" style="table-layout: fixed; text-align:center;">
		<tr>
			<?php 
				if(!$school && !$sem && !$schoolyear){
					echo '<th colspan="4"></th>';
				}elseif($school && $sem && $schoolyear){
					echo '<th></th>';
				}elseif($school && $sem || $school && $schoolyear || $sem && $schoolyear){
					echo '
					<th colspan="2"></th>';
					
				}elseif($school || $sem || $schoolyear){
					echo '
					<th colspan="3"></th>';
				}
			 ?>
			<th colspan="4">Teaching</th>
			<th colspan="2">Non-Teaching</th>
			<th></th>
		</tr>
		<tr style="font-size: 9pt;">
			<th style="width: 2%;">#</th>

			<?php 
				if(!$school){
					echo '<th style="width: 5%;">School / Department</th>';
				}

				if(!$sem){
					echo "<th style='width: 7%;'> Semester</th>";
				}

				if(!$schoolyear){
					echo "<th style='width: 7%;'> School Year</th>";
				}
			 ?>
			 <th style='width: 7%;'>Permanent</th>
			 <th style='width: 7%;'>Probationary</th>
			 <th style='width: 7%;'>Contractual</th>
			 <th style='width: 7%;'>Partime</th>
			 <th style='width: 7%;'>Permanent</th>
			 <th style='width: 7%;'>Probationary</th>
			 <th style='width: 7%;'>Total</th>
			
		</tr>

		<?php 
			$count = 0;
			$t=0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';
						if(!$school){
							echo '<td>'.$q->department.'</td>';
						}

						if(!$sem){
							echo '<td>'.$q->semester.'</td>';
						}
				
						if(!$schoolyear){
							echo '<td>'.$q->school_year.'</td>';
						}	
				echo '
					  	<td>'.$q->no_Tpermanent.'</td>';
				echo '
					  	<td>'.$q->no_Tprobationary.'</td>';	
				echo '
					  	<td>'.$q->no_Tcontractual.'</td>';	
				echo '
					  	<td>'.$q->no_Tpartime.'</td>';	
				echo '
					  	<td>'.$q->no_NTpermanent.'</td>';	
				echo '
						  <td>'.$q->no_NTprobationary.'</td>';
				$sum = $q->no_Tpermanent+$q->no_Tprobationary+$q->no_Tcontractual+$q->no_Tpartime+$q->no_NTpermanent+$q->no_NTprobationary;
					 echo' 	<td>'.$sum.'</td>	
					  </tr>';
					  $t+= $sum;
			}
			echo '<tr>';
				if(!$school && !$sem && !$schoolyear){
					echo '<td style="text-align: right;" colspan="10"><strong>Total:</strong></td>';
				}elseif($school && $sem && $schoolyear){
					echo '<td style="text-align: right;" colspan="7"><strong>Total:</strong></td>';
				}elseif($school && $sem || $school && $schoolyear || $sem && $schoolyear){
					echo '
					<td style="text-align: right;" colspan="8"><strong>Total:</strong></td>';
					
				}elseif($school || $sem || $schoolyear){
					echo '
					<td style="text-align: right;" colspan="9"><strong>Total:</strong></td>';
				}
				
				echo'<td>'.$t.'</td>
				</tr>';
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?><br>
			<?php
					   date_default_timezone_set('Asia/Hong_Kong');
					echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
		</label>
	</div>
</div>	

	</main>
</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/QuantitativeReport\Resources/views/reports/employee-report.blade.php ENDPATH**/ ?>