<!DOCTYPE html>
<html>
<head>
	<title>LIST OF UNIVERSITY PARTNERS</title>
<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<main>
<div class="row">	
	<center><h3>Lists of University Partners</h3></center>
<div>
	<?php 
	if($status != 'All')
	echo '<span class="filters" ><strong>Status:</strong> '.$status.'</span><br>';
		if($from != 'All' && $to!= 'All' )
			echo '<span class="filters" ><strong>From:</strong> '.$from.'<strong>&nbsp;&nbsp;&nbsp;To:&nbsp;&nbsp;</strong> '.$to.'</span><br>';
	 ?>
	</div>
	 <table id="partnerList_table"  class="display compact cell-border" style="text-align: center;">
		
		<?php if($name == null): ?>
        <thead>
          <tr>
			<th style="width: 4%;"></th>
			<th>Company Name</th>
            <th>Scope</th>
            <th>Classification</th>
            <th>Validity</th>
           </tr>
		</thead>
         <tbody>

		<?php 
			$count = 0;
			
	 foreach($partnerList as $pl){
			foreach ($queryBuilder as $q) {
				if($q->company_name == $pl){
				$count++;
				echo '<tr>
				<td>'.$count.'</td>';
				
				echo '
				<td>'.$q->company_name.'</td>';

				echo '
					  	<td>'.$q->scope.'</td>';
					  
				 echo '<td>'.$q->classification.
				
				'</td>';
				 $from = date('M. d, Y', strtotime($q->from));
				 $to = date('M. d, Y', strtotime($q->to));

				 echo '<td>'.$from.' - '.$to.'</td>';
				echo '
					  </tr>';
			}
		}
		}
		 ?>
		</tbody>
		<?php else: ?>
		<?php $__currentLoopData = $partnerList; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pl): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <thead>
		<tr>
				<th colspan="4" style="text-align: left;"><?php echo e($pl); ?></th>
			</tr>
		
          <tr>
			<th style="width: 4%;"></th>
            <th>Scope</th>
            <th>Classification</th>
            <th>Validity</th>
           </tr>
		</thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->company_name == $pl){
				$count++;
				echo '<tr>
				<td>'.$count.'</td>';

				echo '
					  	<td>'.$q->scope.'</td>';
					  
				 echo '<td>'.$q->classification.
				
				'</td>';
				 $from = date('M. d, Y', strtotime($q->from));
				 $to = date('M. d, Y', strtotime($q->to));

				 echo '<td>'.$from.' - '.$to.'</td>';
				echo '
					  </tr>';
			}
		}
		 ?>
		</tbody>
		<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
		<?php endif; ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?><br><?php
	   
			date_default_timezone_set('Asia/Hong_Kong');
			echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
		</label>
	</div>
</div>
		  </main>
</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/Partner\Resources/views/reports/partnerList-report.blade.php ENDPATH**/ ?>