<!DOCTYPE html>
<html>
<head>
	<title>SCHOOL AWARD</title>
	<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
	<main>
<div class="row"><br>
	<center><h3>School Awards And Recognition <?php if($from != 'All' && $to != 'All'): ?> (<?php echo e($from); ?> - <?php echo e($to); ?>)<?php endif; ?></h3></center>
<div>
	<?php 
		if($award != 'All')
			echo '<span class="filters"><strong>Award:</strong> '.$award.'</span>';
		if($school != 'All')
			echo '<span class="filters"><strong>School:</strong> '.$school.'</span>';
	 ?>
	</div>
	<table class="bordered" style="table-layout: fixed;">
		<tr style="font-size: 9pt;">
			<th style="width: 2%;"></th>

			<?php 
			
			if($school == 'All'){
					echo "<th > School</th>";
				}
				if($award == 'All'){
					echo "<th > Award Title</th>";
				}
			 ?>
			 <th>Validity From</th>
			 <th >Validity To</th>
			<th >Venue</th>
			 <th >Award Giving Body</th>
			<th >Supporting Document</th>
			
		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';
						if(!$school){
							echo '<td>'.$q->school_name.'</td>';
						}
						if(!$award){
							echo '<td>'.$q->award.'</td>';
						}
					if($q->from != ""){
						$dfrom = date('M. d, Y', strtotime($q->from));
					  }else{
					  	$dfrom = "";
					  }
				echo '
					  	<td>'.$dfrom.'</td>';

					  if($q->to != ""){
						$dto = date('M. d, Y', strtotime($q->to));
					  }else{
					  	$dto = "";
					  }
				echo '
					  	<td>'.$dto.'</td>';
					  	
					  	if($q->supporting_doc != ""){
					  		$text = "With Document";
					  	}else
					  		$text = "No Attachment";	
				echo '
					  	<td>'.$q->venue.'</td>';	
				echo '
					  	<td>'.$q->award_giving_body.'</td>';	

					  	if($q->supporting_doc != ""){
					  		$text = "With Document";
					  	}else
					  		$text = "No Attachment";
				echo '
					  	<td>'.$text.'</td>
					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?><br><?php
	   
			date_default_timezone_set('Asia/Hong_Kong');
			echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
		</label>
	</div>
</div>
		</main>

</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/Award\Resources/views/reports/schoolAwards-report.blade.php ENDPATH**/ ?>