<!DOCTYPE html>
<html>
<head>
	<title>LISTS OF LICENSURE EXAMS</title>
<?php echo $__env->make('include.report_header', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<main>
<div class="row">	
	<center><h3>Lists of Licensure Exams <?php if($min != "All"): ?>(<?php echo e($min); ?>-<?php echo e($max); ?>)<?php endif; ?></h3></center>
<div>
	<?php 
	
	if($month != "All" && $year != "All")
	echo '<span class="filters" ><strong>Exam Month:</strong> '.$month.' '.$year.'</span><br>';
		if($month != "All" && !$year != "All")
			echo '<span class="filters" ><strong>Exam Month:</strong> '.$month.'</span><br>';
		if($year != "All" && !$month != "All")
			echo '<span class="filters" ><strong>Exam Year:</strong> '.$month.'</span><br>';
	 ?>
	</div>
	 <table class="display compact cell-border" style="text-align: center;">
	 <?php $__currentLoopData = $licensure_exam; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $le): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
        <thead>
		<tr>
				<th colspan="3" style="text-align: left;"><?php echo e($le); ?></th>
			</tr>
          <tr>
		  
			<th style="width:19%">Examination Date</th>
            <th style="width:19%" >Topnotchers</th>
			<th style="width:19%" >School Rank</th>
		  </tr>
        </thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->licensure_exam == $le){
				$count++;
				echo '<tr>
						<td>'.$q->exam_month.' '.$q->exam_year.'</td>';

                          $countTopnotcher = $topnotcherQuery->
                          where('boardexam_id', $q->id)->
						  count();
						  if($countTopnotcher > 1)
						$top = $topnotcherQuery->where('boardexam_id', $q->id)->get();
						else
						$top = $topnotcherQuery->where('boardexam_id', $q->id)->first();
				echo '
						  <td>';
							for($i=0; $i < $countTopnotcher; $i++){
								echo ''.$top->name.'';
							}
				echo '</td> <td>';
				if($q->school_rank != 0)
					 echo''.$q->school_rank.'';
				
				echo '</td></tr>';
			}
		}
		 ?>
		</tbody>
		<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<?php echo e(auth()->user()->first_name); ?> <?php if(auth()->user()->middle_initial != null): ?><?php echo e(auth()->user()->middle_initial); ?>.<?php endif; ?> <?php echo e(auth()->user()->last_name); ?><br>
			<?php echo e($department->school_name); ?><br>
		<?php
	   			date_default_timezone_set('Asia/Hong_Kong');
				echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
				</label>
		</label>
	</div>
</div>
</main>

</body>
</html><?php /**PATH C:\xampp\htdocs\Accreditation\Modules/BoardExam\Resources/views/reports/boardList-report.blade.php ENDPATH**/ ?>