<!DOCTYPE html>
<html>
<head>
	<title></title>
	@include('include.report_header')
	<main>
<div class="row"><br>
	<center><h3>Alumni Survey @if($schoolyear) ({{$schoolyear}})@endif</h3></center>
<div>
	<?php 
		if($school)
			echo '<span class="filters"><strong>School:</strong> '.$school.'</span>';
			
		if($program)
		echo '<span class="filters"><strong>Program:</strong> '.$program.'</span>';
		
		
		if($question)
		echo '<br><span class="filters"><strong>Question:</strong> '.$question.'</span>';

	 ?>
	</div>
    <br>
	<table class="bordered" style="table-layout: fixed;">
		<tr style="font-size: 9pt;">
			<th style="width: 1%;"></th>

			<?php 
				if(!$school){
					echo "<th style='width: 7%;'>School</th>";
				}
				if(!$program){
					echo "<th style='width: 7%;'>Program</th>";
				}
				
                if(!$question){
					echo "<th style='width: 15%;'>Question/s</th>";
				}
			 ?>
			 <th style="width: 10%;">Answer/s</th>
			
		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';

						if(!$school){
							echo '<td>'.$q->school_name.'</td>';
						}
						if(!$program){
							echo '<td>'.$q->acad_prog.'</td>';
						}
						
                        if(!$question){
							echo '<td>'.$q->question.'</td>';
                        }
			
					
						echo '
						  <td>'.$q->answer.'</td>';
					
				echo '
					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
       <label>{{Auth::user()->first_name}} @if(Auth::user()->middle_name != null){{Auth::user()->middle_name}}.@endif {{Auth::user()->last_name}}</label><br>
					
			{{$department->school_code}} {{auth()->user()->user_role}}
		</label>
	</div>
</div>
		</main>

</body>
</html>