<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
            /** Define the margins of your page **/
             @page {
                margin: 50px 70px 70px 70px;
            }
            header {
                position: fixed;
                top: -60px;
                left: 0px;
                right: 0px;

                text-align: center;
                line-height: 35px;
            }

            footer {
                position: fixed; 
                bottom: -60px; 
                left: 0px; 
                right: 0px;
                height: 50px; 

                text-align: right;
                line-height: 35px;
            }
            p, label{
			    padding : 0;
			    margin-top : 0;
			    line-height : 20px;
			}
			table {
			  border-collapse: collapse;
			  width: 100%;
			  table-layout:fixed;
			}

			table, th, td {
			  border: 1px solid black;
			  padding: 3px;
			  font-size:15px;
			  word-wrap:break-word;
			}
			.filters{
				padding-right: 30px;
			}
			footer {
	                position: fixed; 
	                bottom: -60px; 
	                left: 0px; 
	                right: 0px;
	                height: 50px; 
	        }
	        .sans{
	        	font-family: Arial, Helvetica, sans-serif;

	        }
	        .column {
			  float: left;
			  width: 33.33%;/* Should be removed. Only for demonstration */
			}

			/* Clear floats after the columns */
			.row:after {
			  content: "";
			  display: table;
			  clear: both;
			}
        </style>
</head>
<body>
          <br>
            <center><img src="{{asset('images/ubname.png')}}" style="width:20%;margin-bottom: 0;">
            	<p><b>{{$department->school_name}}</b><br>General Luna Rd., Baguio City, Philippines 2600</p>
            </center>
              <hr style="margin-top:0; margin-bottom:0;border:1px solid #000000;">
              <div class="row">
              	<div class="column">
           	  	  <label style="font-size: 12px;">Telefax No.: (074) 619-0003</label>
           		</div>
           		<div class="column" style="text-align: center;"> 
                  <label style=" font-size: 12px; ">Website:www.ubaguio.edu</label>
           		</div>
           		<div class="column" style="text-align: right;">
               	  <label style="font-size: 12px;"> Email Address: registrar@ubaguio.edu</label>
               	</div>
           </div>
<br>
<div class="row">	
<div>
	<center><h3>Student's Award</h3></center>
</div>
<div>
	<?php 
		if($scope)
			echo '<span class="filters"><strong>Scope:</strong> '.$scope.'</span>';
		if($category)
			echo '<span class="filters"><strong>Category:</strong> '.$category.'</span>';

		if($from && $to)
			echo '<span class="filters" ><strong>From:</strong> '.date('M, d Y', strtotime($from)).'<strong>&nbsp;&nbsp;&nbsp;To:&nbsp;&nbsp;</strong> '.date('M, d Y', strtotime($to)).'</span><br>';
	 ?>
	</div>
	<table class="bordered" style="table-layout: fixed;">
		<tr style="font-size: 9pt;">
			<th style="width: 2%;"></th>

			<th style="width: 11%;">Student Name</th>
			<?php 
				if(!$scope){
					echo "<th style='width: 7%;'> Scope</th>";
				}
			 ?>
			<?php 
				if(!$category){
					echo "<th style='width: 7%;'> Category</th>";
				}
			 ?>
			 <th style="width: 7%;">Award</th>
			 <th style="width: 9%;">Classification</th>
			 <th style="width: 16%;">Competition</th>
			 <th style="width: 16%;">Award Giving Body</th>
			<th style="width: 9%;">Date Awarded</th>
			<th style="width: 16%;">Venue</th>
			
		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';

				echo '
					  	<td>'.$q->first_name.', '.$q->middle_initial.'. '.$q->last_name.'</td>';
						if(!$scope){
							echo '<td>'.$q->scope.'</td>';
						}
				
						if(!$category){
							echo '<td>'.$q->category.'</td>';
						}	
				echo '
					  	<td>'.$q->award.'</td>';
				echo '
					  	<td>'.$q->classification.'</td>';	
				echo '
					  	<td>'.$q->title_competitions.'</td>';	
				echo '
					  	<td>'.$q->award_giving_body.'</td>';	
				echo '
					  	<td>'.date('M. d, Y', strtotime($q->date_awarded)).'</td>';
				echo '
					  	<td>'.$q->venue.'</td>
					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br>
			{{auth()->user()->name}}<br>
			{{$department->school_name}}
		</label>
	</div>
</div>


<footer>
 <?php echo date('F, d Y') ?>
</footer>
</body>
</html>