<!DOCTYPE html>
<html>
<head>
	<title></title>
	@include('include.report_header')
	<main>
<div class="row"><br>
	<center><h3>Graduates @if($schoolyear) {{$schoolyear}}@endif</h3></center>
<div>
	<?php 
		if($school)
			echo '<span class="filters"><strong>School:</strong> '.$school.'</span>';
			
		if($program)
		echo '<span class="filters"><strong>Program:</strong> '.$program.'</span>';
		
		if($sem)
			echo '<span class="filters"><strong>Semester:</strong> '.$sem.'</span>';
			
		if($schoolyear)
		echo '<span class="filters"><strong>School Year:</strong> '.$schoolyear.'</span>';

	 ?>
	</div>
	<table class="bordered" style="table-layout: fixed;">
		<tr style="font-size: 9pt;">
			<th style="width: 2%;"></th>

			<?php 
				if(!$school){
					echo "<th style='width: 7%;'>School</th>";
				}
				if(!$program){
					echo "<th style='width: 7%;'>Program</th>";
				}
				if(!$sem){
					echo "<th style='width: 7%;'>Semester</th>";
				}
				if(!$schoolyear){
					echo "<th style='width: 7%;'>School Year</th>";
				}
			 ?>
			 <th style="width: 7%;">ID Number</th>
			 <th style="width: 9%;">Name</th>
			
		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td>'.$count.'</td>';

						if(!$school){
							echo '<td>'.$q->school_name.'</td>';
						}
						if(!$program){
							echo '<td>'.$q->acad_prog.'</td>';
						}
						if(!$sem){
							echo '<td>'.$q->semester.'</td>';
						}
					  	
						if(!$schoolyear){
							echo '<td>'.$q->school_year.'</td>';
						}
				echo '
						  <td>'.$q->id_number.'</td>';	
					if($q->middle_name != ""){
				echo '
						  <td>'.$q->first_name.', '.$q->middle_name.'. '.$q->last_name.'</td>';
					}else{
						echo '
						  <td>'.$q->first_name.', '.$q->last_name.'</td>';
					}
				echo '
					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			<label>{{Auth::guard('alumni')->user()->first_name}} @if(Auth::guard('alumni')->user()->middle_name != null){{Auth::guard('alumni')->user()->middle_name}}.@endif {{Auth::guard('alumni')->user()->last_name}}</label><br>
						 
				 {{$department->school_code}} {{auth()->guard('alumni')->user()->user_role}}
			 </label>
	</div>
</div>
		</main>

</body>
</html>