<!DOCTYPE html>
<html>
<head>
	<title></title>
	@include('include.report_header')
</head>
	<main>
<div class="row">
	<center><strong>@if($sem == '2nd Semester')May @else December @endif @if($schoolyear) 
		<?php $yr = explode(' -',$schoolyear); ?>
		{{$yr[1]}}@endif Graduating Students Feedback  </strong>
	<?php 
	 if($school == 'ALL' && $questionSelected == null){
		$respondents =  $queryBuilder->groupBy('alumni_id')->count();
		echo '<br><label>'.$respondents.' Respondent/s</label>';
	 }
	
	  if($school != 'ALL' && $school != null ){
		  echo '<br><label>'.$schoolname->school_name.'</label>';
	  }
	 	 $acad_prog = $progname->where('id',$program)->first();
		
	 if($program != 'ALL' && $program != null){
		 echo '<br><label>'.$acad_prog->acad_prog.'</label>';
	 }
	 ?></center>
	<br>
	<div class="col-md-10">
	
		<?php
		 $count =1;
	if($school == 'ALL'){
		foreach($questionList as $qlist){
			if($questionSelected == null){
				$new = $queryBuilder->where('q_id',$qlist->id);echo '<label><br>'.$qlist->question.'</label>';
					$cp=0; $email=0; $messenger=0; 
				?>@include('common.report')<?php
			}else{
				$c = count($questionSelected);
				for ($i=0; $i<$c; $i++){
					if($qlist->id == $questionSelected[$i]){
					$respondents =  $queryBuilder->where('q_id',$questionSelected[$i])->count();
					$new = $queryBuilder->where('q_id',$questionSelected[$i]);
					echo '<label><br>'.$qlist->question.' ('.$respondents.' Respondent/s)</label>';
						
					?>@include('common.report')<?php
					}
				}
			}
		}
}elseif($school != 'ALL' && $program == 'ALL' || $program == null){
	foreach($schoolList as $schoolname => $schoolid){
		if($school == 'ALL' || $school == null)echo '<strong>'.$count.'. '.$schoolname.'</strong><br />';
		$count++;	
		foreach($programList as $pname => $pschoolid){
		if($schoolid == $pschoolid){
			$acad_prog = $progname->where('id',$pname)->first();
			$respondents =  $queryBuilder->where('school_id',$schoolid)->where('program_id',$acad_prog->id)->groupBy('alumni_id')->count();
		if($program == 'ALL' || $program == null)echo '<strong><br>'.$acad_prog->acad_prog.'('.$respondents.' Respondent/s)</strong>';
		$count++;
	 foreach($questionList as $qlist){
		if($questionSelected == null){
			$new = $queryBuilder->where('q_id',$qlist->id)->where('school_id',$schoolid)->where('program_id',$acad_prog->id);
			echo '<label><br>'.$qlist->question.'</label>';
				?>@include('common.report')<?php
			}else{
				$c = count($questionSelected);
				for ($i=0; $i<$c; $i++){
					if($qlist->id == $questionSelected[$i]){
					$new = $queryBuilder->where('q_id',$questionSelected[$i])->where('school_id',$schoolid)->where('program_id',$acad_prog->id);
					echo '<label><br>'.$qlist->question.'</label>';
					?>@include('common.report')<?php
					}
				}
			}
		  }
		}
		}
	}
}else{
	foreach($schoolList as $schoolname => $schoolid){
		if($school == 'ALL' || $school == null)echo '<strong>'.$count.'. '.$schoolname.'</strong><br />';
		$count++;
	foreach($programList as $pname => $pschoolid){
		if($schoolid == $pschoolid){
			$acad_prog = $progname->where('id',$pname)->first();
			$respondents =  $queryBuilder->where('id',$pname)->groupBy('alumni_id')->count();
		if($program == 'ALL' || $program == null)echo '<strong><br>'.$acad_prog->acad_prog.'</strong>';
		echo '<strong><br>'.$respondents.' Respondent/s</strong>';
	 foreach($questionList as $qlist){
		if($questionSelected == null){
			$new = $queryBuilder->where('q_id',$qlist->id)->where('program_id',$pname);
			echo '<label><br>'.$qlist->question.'</label>';
				?>@include('common.report')<?php
			}else{
				$c = count($questionSelected);
				for ($i=0; $i<$c; $i++){
					if($qlist->id == $questionSelected[$i]){
					$new = $queryBuilder->where('q_id',$questionSelected[$i])->where('program_id',$pname);
					echo '<label><br>'.$qlist->question.'</label>';
					?>@include('common.report')<?php
					}
				}
			}
		
			}
		  }
		}
	}
}

		 ?>
</div>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
	   <label>{{Auth::guard('alumni')->user()->first_name}} @if(Auth::guard('alumni')->user()->middle_name != null){{Auth::guard('alumni')->user()->middle_name}}.@endif {{Auth::guard('alumni')->user()->last_name}}</label><br>
	   <label><?php
	   
		date_default_timezone_set('Asia/Hong_Kong');
		echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
		</label>
	</div>
</div>
		</main>

</body>
</html>