
<!DOCTYPE html>
<html>
<head>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>ACADEMIC PROGRAMS</title>
	@include('include.report_header')
	<main>
<body>
<div class="row">
@if($school)
<center><strong>{{$list->school_name}} Academic Programs</strong></center><br>
	<table>
        <tr>
			<th style="width:20%;">Program Code</th>
			<th style="width:80%;">Program Description</th>
		</tr>
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
                if($q->school_id == $list->id){
				echo '<tr>';
							echo '<td>'.$q->acad_prog_code.'</td>';
						
				echo '
					  	<td>'.$q->acad_prog.'</td>

                      </tr>';
                    }
			}
         ?>
    </table><br>
@else
<center><h3>List of Schools and Academic Programs</h3></center>
<?php $category = ['Graduate Programs','Undergrad Program','Basic Educatioon'] ?>
@for($i = 0; $i < count($category); $i++)
<strong>{{$category[$i]}}</strong>
	<table>
		<tr>
			<th style="width:15%;">School Code</th>
			<th style="width:15%;">Program Code</th>
			<th style="width:70%;">Program Description</th>
		</tr>
@foreach($list as $l)
<?php $f = substr($l->school_name, 0, 1); ?>
 @if($i == 0 )
	@if($l->school_code == 'GS')
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->school_id == $l->id){
				echo '<tr>
					<td>'.$q->school_code.'</td>
					<td>'.$q->acad_prog_code.'</td>
					<td>'.$q->acad_prog.'</td>

					</tr>';
					}
			}
		?>
		@endif
 @elseif($i == 1)
	@if($f == 'S')
		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->school_id == $l->id){
					echo '<tr>
					<td>'.$q->school_code.'</td>
					<td>'.$q->acad_prog_code.'</td>
					<td>'.$q->acad_prog.'</td>

					</tr>';
					}
				}
		?>
	@endif
@else
	@if($f != 'S' && $l->school_code != 'GS')
	<?php 
		$count = 0;
		foreach ($queryBuilder as $q) {
			if($q->school_id == $l->id){
				echo '<tr>
				<td>'.$q->school_code.'</td>
				<td>'.$q->acad_prog_code.'</td>
				<td>'.$q->acad_prog.'</td>

				  </tr>';
				}
		}
	 ?>
	 @endif
	@endif
	@endforeach
</table><br>
	@endfor
@endif
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
	   {{auth()->user()->first_name}} @if(auth()->user()->middle_initial != null){{auth()->user()->middle_initial}}.@endif {{auth()->user()->last_name}}<br>
	   <label><?php
	   
		date_default_timezone_set('Asia/Hong_Kong');
		echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
	</div>
</div>
		</main>
</body>
</html>