
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>LEVEL OF ACCREDITATION</title>
	@include('include.report_header')
	<main>
<div class="row">
<center><h3>LEVEL OF ACCREDITATION @if($min != 'All' && $max != 'All') ({{$min}} - {{$max}}) @endif</h3></center>
<div>
	<?php 

		if($school)
			echo '<span class="filters"><strong>School:</strong> '.$school.'</span><br>';
		if($accredStatus)
			echo '<span class="filters"><strong>Accreditation Level:</strong> '.$accredStatus.'</span><br>';

		if($expiry == 'Active')
			echo '<span class="filters"><strong>Status:</strong> Active</span><br>';
		else if($expiry == 'Expired')
			echo '<span class="filters"><strong>Status:</strong> Expired</span><br>';

			echo "<p>";

		if($visitYear && $min && $max )
			echo '<label class="filters"><strong>Visitation Year:</strong> '.$visitYear.'</label><br>';
		else if ($visitYear)
			echo '<label class="filters"><strong>Visitation Year:</strong> '.$visitYear.'</label><br>';

		echo "</p>";
	 ?>
</div>
	<table class="display compact cell-border" style="text-align: center;">
		<tr>
			<th style="width: 5%;" ></th>
			<?php 
				if(!$school){
					echo '<th style="width: 10%; ">SCHOOL</th>';
				}
			 ?>
			
			<th style="width: 25%;">PROGRAM</th>
			<?php 
				if(!$accredStatus){
					echo '<th style="width: 20%;"> LEVEL OF ACCREDITATION
</th>';
				}
			 ?>
			<th style="width: 20%;">DURATION</th>
			<th style="width: 20%;">REMARKS</th>

		</tr>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				$count++;
				echo '<tr>
						<td style="text-align:center;">'.$count.'.</td>';
						if(!$school){
							echo '<td style="text-align:center;">'.$q->school_code.'</td>';
						}
				echo '
					  	<td>'.$q->acad_prog.'</td>';
						if(!$accredStatus){
							echo '<td>'.$q->accred_status.'</td>';
						}
				echo '
					  	<td style="text-align:center;">'.date('F Y', strtotime($q->from)).' - '.date('F Y', strtotime($q->to)).'</td>
					  	<td style="text-align:center;">'.$q->remarks.'</td>

					  </tr>';
			}
		 ?>
	</table>
	<div style="margin-top: 50px;"><label>Generated by:<br><br>
		<label>{{auth()->user()->first_name}} @if(auth()->user()->middle_initial != null){{auth()->user()->middle_initial}}.@endif {{auth()->user()->last_name}}<br>
			{{$department->school_name}}</label><br>
		<label><?php
		
		 date_default_timezone_set('Asia/Hong_Kong');
		 echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
		 </label>
	</div>
</div>
		</main>
</body>
</html>