<!DOCTYPE html>
<html>
<head>
	<title>LISTS OF LICENSURE EXAMS</title>
@include('include.report_header')
<main>
<div class="row">	
	<center><h3>Lists of Licensure Exams @if($min != "All")({{$min}}-{{$max}})@endif</h3></center>
<div>
	<?php 
	
	if($month != "All" && $year != "All")
	echo '<span class="filters" ><strong>Exam Month:</strong> '.$month.' '.$year.'</span><br>';
		if($month != "All" && !$year != "All")
			echo '<span class="filters" ><strong>Exam Month:</strong> '.$month.'</span><br>';
		if($year != "All" && !$month != "All")
			echo '<span class="filters" ><strong>Exam Year:</strong> '.$month.'</span><br>';
	 ?>
	</div>
	 <table class="display compact cell-border" style="text-align: center;">
	 @foreach($licensure_exam as $le)
        <thead>
		<tr>
				<th colspan="3" style="text-align: left;">{{$le}}</th>
			</tr>
          <tr>
		  
			<th style="width:19%">Examination Date</th>
            <th style="width:19%" >Topnotchers</th>
			<th style="width:19%" >School Rank</th>
		  </tr>
        </thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->licensure_exam == $le){
				$count++;
				echo '<tr>
						<td>'.$q->exam_month.' '.$q->exam_year.'</td>';

                          $countTopnotcher = $topnotcherQuery->
                          where('boardexam_id', $q->id)->
						  count();
						  if($countTopnotcher > 1)
						$top = $topnotcherQuery->where('boardexam_id', $q->id)->get();
						else
						$top = $topnotcherQuery->where('boardexam_id', $q->id)->first();
				echo '
						  <td>';
							for($i=0; $i < $countTopnotcher; $i++){
								echo ''.$top->name.'';
							}
				echo '</td> <td>';
				if($q->school_rank != 0)
					 echo''.$q->school_rank.'';
				
				echo '</td></tr>';
			}
		}
		 ?>
		</tbody>
		@endforeach
	</table>
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			{{auth()->user()->first_name}} @if(auth()->user()->middle_initial != null){{auth()->user()->middle_initial}}.@endif {{auth()->user()->last_name}}<br>
			{{$department->school_name}}<br>
		<?php
	   			date_default_timezone_set('Asia/Hong_Kong');
				echo '<label>'.date('M d,Y h:i:sa').'</label>';?>
				</label>
		</label>
	</div>
</div>
</main>

</body>
</html>