<!DOCTYPE html>
<html>
<head>
	<title>BOARD TOPNOTCHERS</title>
@include('include.report_header')
<main>
<div class="row">	
<div>
	<?php 
	if($month)
	echo '<span class="filters"><strong>Month:</strong> '.$month.'</span>';
	   if($year)
			echo '<span class="filters"><strong>Year:</strong> '.$year.'</span>';
		if($rank)
			echo '<span class="filters"><strong>Rank:</strong> '.$rank.'</span>';	
	 ?>
	</div>
	@if($var != "")
	<?php $C = count($var); ?>
	@for($i=0; $i < $C; $i++)
	<?php $var1 = $var[$i];?>
	<div>
		<center><h3> @if($var1 == "SBT")
			Summary of Board Topnotchers 
			@elseif($var1 == "STS")
			Summary of Top Schools 
			@else
			Universiy of Baguio Board Topnotchers 
			@endif
			@if($min != "All")({{$min}}-{{$max}})@endif
			</h3></center>
		</div>
	@if($var1 == "SBT")
	 <table  class="display compact cell-border" style="text-align: center;">
        <thead>
          <tr>
            <th>Program</th>
            <?php 
				if($min != 'All'){	
					$x = $min;
					$y = $max;
					for($x; $x <= $y; $x++){
						echo '<th>'.$x.'</th>';
					}
				}
			 ?>
           </tr>
        </thead>
         <tbody>
		<?php 
		$queryBuilder = $queryBuilder->where('rank','>',0);
          
			foreach ($queryBuilder as $q) {
				
			$x =$min;
			$y =$max;
				echo '<tr>
						  <td>'.$q->licensure_exam.'</td>';
				for($x; $x <= $y; $x++){
					if($q->exam_year == $x){
					echo '<td> Rank '.$q->rank.'</th>';
					}else{
						echo '<td></td>';
					}
				}	
				echo '
					  </tr>';
			}
		 ?>
		</tbody>
	</table>
	@elseif($var1 == "STS")
	<table  class="display compact cell-border" style="text-align: center;">
        <thead>
          <tr>
            <th>Program</th>
            <?php 
				if($min != 'All'){	
					$x = $min;
					$y = $max;
					for($x; $x <= $y; $x++){
						echo '<th>'.$x.'</th>';
					}
				}
			 ?>
           </tr>
        </thead>
         <tbody>
		<?php 
		$queryBuilder = $queryBuilder->where('school_rank','>',0);
			foreach ($queryBuilder as $q) {
				
			$x =$min;
			$y =$max;
				echo '<tr>
						  <td>'.$q->licensure_exam.'</td>';
				for($x; $x <= $y; $x++){
					if($q->exam_year == $x){
					echo '<td> Rank '.$q->school_rank.'</th>';
					}else{
						echo '<td></td>';
					}
				}	
				echo '
					  </tr>';
			}
		 ?>
		</tbody>
	</table>
@else
		<table id="history_table"  class="display compact cell-border" style="text-align: center;">
	 @foreach($licensure_exam as $le)
        <thead>
			<tr>
				<?php 
				if(!$rank || !$min){
				 echo "<th colspan='3' style='text-align: left;'>$le</th>";
				}else
					echo "<th colspan='2' style='text-align: left;'>$le</th>";
				?>
			</tr>
          <tr>
		  
		  <?php 
		  		echo "<th>Name</th>";
			 ?>
            <th>Examination Date</th>
            <?php 
				if(!$rank){
					echo "<th>Rank</th>";
				}
			 ?>
           </tr>
        </thead>
         <tbody>

		<?php 
			$count = 0;
			foreach ($queryBuilder as $q) {
				if($q->licensure_exam == $le){
				$count++;
				echo '<tr>
					  	<td>'.$q->name.'</td>
						
					  	<td>'.$q->exam_month.' '.$q->exam_year.'</td>';
						
					  
				if(!$rank){
					if($q->rank == 1)
						$sup = 'st';
				elseif($q->rank == 2)
						$sup = 'nd';
					elseif($q->rank == 3)
					$sup = 'rd';
					else
					$sup = 'th';
				 echo '<td>'.$q->rank.'<sup>'.$sup.'</sup> Place </td>';
						}
				echo '
					  </tr>';
					}
			}
		 ?>
		</tbody>
		@endforeach
	</table>
	@endif
	@endfor
	@endif
	<div style="margin-top: 50px;">
		<label>Generated by:<br><br>
			{{auth()->user()->first_name}} @if(auth()->user()->middle_initial != null){{auth()->user()->middle_initial}}.@endif {{auth()->user()->last_name}}<br>
			{{$department->school_name}}
		</label>
	</div>
</div>
</main>
</body>
</html>